name: Rust

on:
  push:
    branches: [ "release/*" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  make_osx_release:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prep
      run: cargo install cargo-bundle
    - name: Make bundle
      run: cargo bundle --release --target x86_64-apple-darwin
